name: PetBooster
main: PetBooster\Main
author: Mchtra
version: 1.0.0
api: 5.1.0

commands:
  pet:
    description: Manage your pet
    usage: "/pet menu"
    permission: pet.command

permissions:
  pet.command:
    default: true
